version: "3.7"

services:
  vmq:
    image: ghcr.io/ysoftwareab/docker-vernemq:1.10.3-arm64
    ports:
      - 8080:8080
      - 8888:8888
      - 1883:1883
    volumes:
      - ./etc:/vernemq/etc/
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: yes


